### ISSUE TITLE
Decide on game engine

### ISSUE THREAD

**Issue by archerlmlzmg** [archerlmlzmg/202GroupProject#2]
Decide which game engine to use for game implementation

**Comment by archerlmlzmg** [comment]
do you guys want to use greenfoot or unity?

**Comment by heiheidodo** [comment]
Greenfoot, Unity, Unreal, source2; Processing, Eclipse.

**Comment by XinleiYang** [comment]
firstly I think we can choose java-based engine or just directly use java to write a game
